### PR TITLE
Small improvements

### LINKED ISSUE #122: Wallet created on mainnet has prover = https://testnet.provers.dusk.network
**Describe the bug**
On a fresh install of mainnet v0.5.1 the wallet config file `rusk-wallet/config.toml` links the prover to a non-mainnet resource:
```
state = "http://127.0.0.1:8080"
prover = "https://testnet.provers.dusk.network"
```
I don't know enough about rusk to know if this is a bug, but in general it's problematic for systems to mix network resources between testnet and mainnet...

**To Reproduce**
```
curl --proto '=https' --tlsv1.2 -sSfL https://github.com/dusk-network/node-installer/releases/download/v0.5.1/node-installer.sh | sudo bash
sudo cat ~/.dusk/rusk-wallet/config.toml
```

**Expected behaviour**
I would expect a mainnet installation to only have configurations that point to mainnet resources.

**Platform**
Fill as appropriate
 - Architecture: 8086
 - OS: Linux
 - Distribution: Ubuntu 24.04
 - Browser: N/A

### LINKED ISSUE #124: Remove UFW from the script
#### Summary
Currently the script checks for UFW and installs it if required, and then sets firewall rules. This is too out of scope for an installer script to be handling, and should be removed.

#### Possible solution design or implementation
Remove the UFW use, and instead provide documentation to users on how to configure a firewall.

### PR DESCRIPTION
**Pull request by HDauven**
Resolves #124 #122 #89

This PR:
- Changes download URLs to use the latest release for README download URLs
- Sets the prover URL based on the targeted network
- Adds more documentation on users, groups and firewalls
- Allows non-root users to install the script
- Removes use of UFW
- Fix IP detection on Hetzner

### CODE REVIEW

File: node-installer.sh [hunk 1]
```diff
@@ -240,10 +274,14 @@ rm -rf /opt/dusk/rusk/keys || true
...
 
-chown -R dusk:dusk /opt/dusk/
-
 configure_network "$NETWORK"
 
+# Set permissions for dusk user and group
+chown -R dusk:dusk /opt/dusk
+chmod -R 770 /opt/dusk
+chown -R dusk:dusk /var/log/rusk.log
+chmod -R 770 /var/log/rusk.log
```
Comment (herr-seppia) [inline node-installer.sh:283]: No need to set restrictions for logs

**Comment by HDauven** [comment]
@herr-seppia I've also modified the way we detect IPs. Tested this on both my own machine, DigitalOcean and Hetzner. With the old setup, Hetzner didn't detect the IPs correctly, now all three work as expected.

**Comment by herr-seppia** [comment]
> @herr-seppia I've also modified the way we detect IPs. Tested this on both my own machine, DigitalOcean and Hetzner. With the old setup, Hetzner didn't detect the IPs correctly, now all three work as expected.

Wait
Did you remove the local ip detection too?

It was needed for VPS with different ips

File: bin/detect_ips.sh [hunk 2]
```diff
@@ -1,48 +1,16 @@
...
-                int2ip $ip myIp && int2ip $mask netMask
-        }
-    }
-done < <(/sbin/ifconfig)
-
-echo "KADCAST_PUBLIC_ADDRESS=$PUBLIC_IP:9000"
-if [ -z "$myIp" ]; then
-    echo "KADCAST_LISTEN_ADDRESS=$PUBLIC_IP:9000"
-else
-    echo "KADCAST_LISTEN_ADDRESS=$myIp:9000"
```
Comment (herr-seppia) [inline bin/detect_ips.sh:46]: I'm not sure we should remove the private ip detection too

Comment (HDauven) [reply bin/detect_ips.sh:46]: @herr-seppia you're right! I was being too enthusiastic. This _should_ behave the same as it did before and take the local IP into account again. Tested it on a local machine.

In `curl` I specify the SSL version. Without doing so, it fails on Hetzner for me. DO and local machine seem to be fine without it though.

File: bin/detect_ips.sh [hunk 3]
```diff
@@ -1,48 +1,30 @@
...
+    exit 1
+fi
 
-echo "KADCAST_PUBLIC_ADDRESS=$PUBLIC_IP:9000"
-if [ -z "$myIp" ]; then
-    echo "KADCAST_LISTEN_ADDRESS=$PUBLIC_IP:9000"
-else
-    echo "KADCAST_LISTEN_ADDRESS=$myIp:9000"
+# Detect the local IP (for machines behind NAT or in internal networks)
+LOCAL_IP=$(hostname -I | awk '{print $1}')
```
Comment (herr-seppia) [inline bin/detect_ips.sh:16]: Why did you change the previous mechanism? Wasn't it working?

**Review by herr-seppia — CHANGES_REQUESTED** [review]

File: bin/detect_ips.sh (hunk 3 above)
Comment (HDauven) [reply bin/detect_ips.sh:16]: > Why did you change the previous mechanism? Wasn't it working?

ifconfig/route/net-tools has been deprecated by many distros and replaced by utils like more modern utils like `ip` and `iproute2`. I didn't use those because this is much simpler and does the trick

Comment (HDauven) [reply bin/detect_ips.sh:16]: https://lists.debian.org/debian-devel/2009/03/msg00780.html

https://www.redhat.com/en/blog/deprecated-linux-command-replacements

File: node-installer.sh [hunk 4]
```diff
@@ -170,20 +189,33 @@ update_pkg_database
...
+    echo "User 'dusk' and group 'dusk' created."
+else
+    echo "User 'dusk' and group 'dusk' already exist."
+fi
+
+# Add the current user to the dusk group for access
+echo "Adding current user to dusk group for access."
+if ! id -nG "$CURRENT_USER" | grep -qw "dusk"; then
+    usermod -aG dusk "$CURRENT_USER"
+    echo "User $CURRENT_USER has been added to the dusk group. Please log out and back in to apply changes."
```
Comment (herr-seppia) [inline node-installer.sh:208]: Does this means that, during an upgrade, people should logout before run "ruskreset"?

**Review by herr-seppia — APPROVED** [review]

File: README.md [hunk 5]
```diff
@@ -43,11 +43,79 @@ The configuration files, binaries, services and scripts can be found in `/opt/du
...
+- `9000/udp` for Kadcast (used for consensus messages)
+
+If you're running an archive node or want to expose the HTTP server, you can also open the corresponding TCP port (default: `8080`).
+
+#### Configure with `ufw`
+
+If you're using `ufw`, you can configure it with these commands:
+```ssh
+# Allow SSH (default port 22)
+sudo ufw allow ssh
```
Comment (BoboTiG) [inline README.md:105]: A little bit more secure:
```suggestion
sudo ufw limit ssh
```

**Review by BoboTiG — APPROVED** [review]

File: README.md (hunk 5 above)
Comment (HDauven) [reply README.md]: > A little bit more secure:

That's actually a really nice one, thank you! Updated

**Review by BoboTiG — APPROVED** [review]

File: node-installer.sh [hunk 6]
```diff
@@ -170,20 +189,33 @@ update_pkg_database
 check_installed unzip unzip
 check_installed curl curl
 check_installed jq jq
-check_installed route net-tools
 check_installed logrotate logrotate
-check_installed dig dnsutils
```
Comment (herr-seppia) [inline node-installer.sh:175]: you should add these back

```
check_installed route net-tools
check_installed dig dnsutils
```
